"""Initial migration

Revision ID: 54e03fe9951c
Revises: 
Create Date: 2024-06-18 10:17:36.914937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54e03fe9951c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_hash', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['uname'])
        batch_op.drop_column('pass_hash2')
        batch_op.drop_column('pass_hash1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_hash1', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('pass_hash2', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pass_hash')

    # ### end Alembic commands ###
